# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "justools"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["caleon"]
  s.date = "2012-10-23"
  s.description = "Core extensions with lots of handy methods"
  s.email = "caleon@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/justools.rb",
    "lib/justools/core_ext.rb",
    "lib/justools/core_ext/array.rb",
    "lib/justools/core_ext/array/args_and_opts.rb",
    "lib/justools/core_ext/array/filters.rb",
    "lib/justools/core_ext/array/flatten_splat.rb",
    "lib/justools/core_ext/array/inquiry.rb",
    "lib/justools/core_ext/array/merge_options.rb",
    "lib/justools/core_ext/class.rb",
    "lib/justools/core_ext/enumerable.rb",
    "lib/justools/core_ext/hash.rb",
    "lib/justools/core_ext/object.rb",
    "lib/justools/core_ext/set.rb",
    "lib/tasks/core_utilities_tasks.rake",
    "spec/justools_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/caleon/justools"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Core extensions with lots of handy methods"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

